exclude: ['README.md']
# baseurl: /paulmcaviney.ca
permalink: /:title/

collection:
  blog:
    output: true
    permalink: /blog/:path/ 

# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: default
#   -
#     scope:
#       path:   
#       type: category
#       values:
#       layout: "category"